version: '3'
services:
  chrome:
    image: easychen/checkchan:latest
    volumes:
      - ./data:/checkchan/data
    environment:
      - CKC_PASSWD=123
      - VDEBUG=OFF
      - VNC=OFF
      - WIN_WIDTH=414
      - WIN_HEIGHT=896
      - XVFB_WHD=500x896x16
      - API_KEY=test
      - ERROR_IMAGE=NONE
      - SNAP_URL_BASE=
      - SNAP_FULL=0
      - WEBHOOK_URL=
      - TZ=Asia/Shanghai
    ports:
      - 5900:5900
      - 8080:8080
      - 8088:80
